---

- name: "Apply s3 backup lifecycle policy on the s3 bucket {{ backup_mongo_bucket_name }}"
  s3_lifecycle:
    rule_id: "{{ _backup_s3_expire_policy.name }}"
    name: "{{ backup_mongo_bucket_name }}"
    transition_days: "{ _backup_s3_expire_policy.glacier_transition }}"
    expiration_days: "{{ _backup_s3_expire_policy.permanently_delete }}"
    prefix: "{{ _backup_s3_expire_policy.prefix }}"
    status: enabled
    state: present
  run_once: true
  delegate_to: 127.0.0.1
  when: _backup_s3_expire_policy.glacier_transition > 0

- name: "Apply s3 backup lifecycle policy on the s3 bucket {{ backup_mongo_bucket_name }}"
  s3_lifecycle:
    rule_id: "{{ _backup_s3_expire_policy.name }}"
    name: "{{ backup_mongo_bucket_name }}"
    expiration_days: "{{ _backup_s3_expire_policy.permanently_delete }}"
    prefix: "{{ _backup_s3_expire_policy.prefix }}"
    status: enabled
    state: present
  run_once: true
  delegate_to: 127.0.0.1
  when: _backup_s3_expire_policy.glacier_transition == 0

- name: "create the local backup path {{ backup_mongo_local_path }}"
  file: path={{ backup_mongo_local_path }} state=directory mode=0755 recurse=yes

- name: "Add mongodb backup script /usr/bin/mongo-backup.sh"
  template: src=mongodb/mongo-backup.sh.j2 dest=/usr/bin/mongo-backup.sh owner=root group=root mode=0755

# Add cron comands
- name: "cron add backup command"
  cron: >
    name="{{ item.name }}"
    job="{{ item.job }}"
    minute={{ item.minute|default('*') }}
    hour={{ item.hour|default('*') }}
    day={{ item.day|default('*') }}
    month={{ item.month|default('*') }}
    weekday={{ item.weekday|default('*') }}
    cron_file={{ item.file|default("mongo_backup") }}
    user={{ backup_mongo_cron_user }}
    state={{ item.state|default('present') }}
  with_items:
    - "{{ _backup_mongo_cron }}"
  sudo: yes 

