---

# Used by aws cli with sudo commands
# If you are not able to change sudo_flags, the HOME variable when using become_user
# will be the HOME from the ssh user.
- name: "Get HOME directory for user {{ backup_mongo_cron_user }}"
  shell: 'getent passwd {{ backup_mongo_cron_user }} | cut -d: -f6'
  register: user_home

# Gen s3 bucket policy for the expire
- name: "Generate s3bucket policy file"
  template: src=s3/lifecycle.json.j2 dest=/var/tmp/s3_backup_policy.json mode=0644
  register: s3_policy


# Apply the s3 policy
- name: "Apply s3 backup lifecycle policy on the s3 bucket {{ backup_mongo_bucket_name }}"
  command: /usr/local/bin/aws s3api put-bucket-lifecycle --bucket {{ backup_mongo_bucket_name }}  --lifecycle-configuration file:///var/tmp/s3_backup_policy.json
  become: yes
  become_user: "{{ backup_mongo_cron_user }}"
  environment:
    HOME: "{{ user_home.stdout }}"

- name: "create the local backup path {{ backup_mongo_local_path }}"
  file: path={{ backup_mongo_local_path }} state=directory mode=0755 recurse=yes

- name: "Add mongodb backup script /usr/bin/mongo-backup.sh"
  template: src=mongodb/mongo-backup.sh.j2 dest=/usr/bin/mongo-backup.sh owner=root group=root mode=0755

# Add cron comands
- name: "cron add backup command"
  cron: >
    name="{{ item.name }}"
    job="{{ item.job }}"
    minute={{ item.minute|default('*') }}
    hour={{ item.hour|default('*') }}
    day={{ item.day|default('*') }}
    month={{ item.month|default('*') }}
    weekday={{ item.weekday|default('*') }}
    cron_file={{ item.file|default("mongo_backup") }}
    user={{ backup_mongo_cron_user }}
    state={{ item.state|default('present') }}
  with_items:
    - "{{ _backup_mongo_cron }}"
  sudo: yes 

