---

- name: "Install required package for mongo backup | Ubuntu / Debian"
  apt:
    name: '{{ item }}'
    cache_valid_time: 3600
    update_cache: yes 
    state: latest
  with_items:
    - cron
    - python-dev
    - build-essential
    - python-pip
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- pip: name=awscli state=latest
  when: _check_aws_cli|failed
