---

# Gen s3 bucket policy for the expire
- name: "Generate s3bucket policy file"
  template: src="{{ ansible_template_path_legacy }}s3/lifecycle.json.j2" dest=/var/tmp/s3_backup_policy.json mode=0644
  register: s3_policy
  run_once: true
  delegate_to: 127.0.0.1
  when: backup_s3_expire_policy.permanently_delete is defined and backup_s3_expire_policy.permanently_delete > 0

# Apply the s3 policy
# For this command, ensure the ssh user have access to s3 bucket
- name: "Apply s3 backup lifecycle policy on the s3 bucket {{ backup_mysql_bucket_name }}"
  command: /usr/local/bin/aws s3api put-bucket-lifecycle --bucket {{ backup_mysql_bucket_name }}  --lifecycle-configuration file:///var/tmp/s3_backup_policy.json
  run_once: true
  delegate_to: 127.0.0.1
  when: backup_s3_expire_policy.permanently_delete is defined and backup_s3_expire_policy.permanently_delete > 0

- name: "create the local backup path {{ backup_mysql_local_path }}"
  file: path={{ backup_mysql_local_path }} state=directory mode=0755 recurse=yes

- name: "Add MySQL db backup script /usr/bin/{{ backup_mysql_script }}.sh"
  template: src="{{ ansible_template_path_legacy }}mysql/mysql-backup.sh.j2" dest=/usr/bin/{{ backup_mysql_script }}.sh owner=root group=root mode=0755

# Add cron comands
- name: "cron add backup command"
  cron: >
    name="{{ item.name | default(default_backup_mysql_cron.name) }}"
    job="{{ item.job | default(default_backup_mysql_cron.job) }}"
    minute="{{ item.minute | default(default_backup_mysql_cron.minute) }}"
    hour="{{ item.hour | default(default_backup_mysql_cron.hour) }}"
    day="{{ item.day | default(default_backup_mysql_cron.day) }}"
    month="{{ item.month | default(default_backup_mysql_cron.month) }}"
    weekday="{{ item.weekday | default(default_backup_mysql_cron.weekday) }}"
    cron_file="{{ item.file | default(default_backup_mysql_cron.cron_file) }}"
    user="{{ backup_mysql_cron_user }}"
    state="{{ item.state | default(default_backup_mysql_cron.state) }}"
  with_items:
    - "{{ backup_mysql_cron }}"
  sudo: yes 
