---
driver:
  name: docker
  use_sudo: false
  require_chef_omnibus: false # No need of chef

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  ansible_verbosity: 2
  ansible_verbose: true
  require_ansible_omnibus: true
  require_chef_for_busser: false # No need of chef
  requirements_path: requirements-test.yml
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  extra_vars:
    aws_default_region: <%= ENV['AWS_DEFAULT_REGION'] %>
    aws_access_key_id: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    aws_secret_access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    backup_es_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>

#additional_copy_path
platforms:
  - name: debian-wheezy
    driver_config:
      image: cycloid
      #image: seraf/wheezy-kitchenci
      platform: debian

suites:
  - name: default
