---

# Check args
 - include: check.yml

# Legacy parameter for copy module with template. In ansible 1.9.4 with multiple include in sub directory we can't
# use simply template. Ansible still looking in task/template/... directory
# Get ansible version
 
 - set_fact:
      ansible_template_path_legacy: '../../templates/'
   when: ansible_version.major < 2

 - set_fact:
      ansible_template_path_legacy: ''
   when: ansible_version.major >= 2

 - include: "{{ backup_type }}.yml"
