---

# Check args
 - include: check.yml
 - include: "{{ backup_type }}.yml"











## Update code deployment step
#- name: Set release version from timestamp
#  set_fact: deployment_release_version="{{ deployment_timestamp.stdout }}"
#  when: deployment_release_version is not defined

#- include: "update-code/{{ deployment_deploy_via | default('rsync') }}.yml"
#  become: yes
#  become_user: '{{ deployment_user }}'


# ############
# # pre_tasks
# ############
# - name: Get release timestamp
#   local_action: command date -u +%Y%m%d%H%M%SZ
#   run_once: true
#   register: deployment_timestamp
#   sudo: no
# 
# - include: slack.yml state=start
#   when: slack
#   tags:
#     - code-deployment
# 
# - include: registry.yml state=start
#   when: deployment_registry
#   tags:
#     - code-deployment
# 
# - supervisorctl: name={{ item }} state=stopped
#   when: deployment_supervisord_enabled and not deployment_supervisord_restart_only
#   with_items: "{{ deployment_supervisord_programs }}"
#   tags:
#     - code-deployment
# 
# - include: sensu.yml stash=true
#   when: deployment_sensu_enabled
#   tags:
#     - code-deployment
# 
# - include: ec2-deregister.yml
#   when: deployment_rolling_elb_enabled
# 
# ############
# # main_tasks
# ############
# 
# - include: "{{ deployment_before_setup_tasks_file | default('empty.yml') }}"
# 
# - include: user.yml
#   tags:
#     - setup-deployment
# 
# - include: setup.yml
#   tags:
#     - setup-deployment
# 
# - include: ansible-dependency.yml
#   tags:
#     - setup-deployment
# 
# - include: "{{ deployment_after_setup_tasks_file | default('empty.yml') }}"
#   tags:
#     - setup-deployment
# 
# - include: "{{ deployment_before_update_code_tasks_file | default('empty.yml') }}"
#   tags:
#     - code-deployment
# 
# - include: update-code.yml
#   when: not deployment_setup_only
#   tags:
#     - code-deployment
# 
# - include: parameters.yml
#   tags:
#     - code-deployment
# 
# - include: "{{ deployment_after_update_code_tasks_file | default('empty.yml') }}"
#   tags:
#     - code-deployment
# 
# - include: "{{ deployment_before_symlink_shared_tasks_file | default('empty.yml') }}"
#   tags:
#     - code-deployment
# 
# - include: symlink-shared.yml
#   when: not deployment_setup_only
#   tags:
#     - code-deployment
# 
# - include: "{{ deployment_after_symlink_shared_tasks_file | default('empty.yml') }}"
#   tags:
#     - code-deployment
# 
# - include: "{{ deployment_before_symlink_tasks_file | default('empty.yml') }}"
#   tags:
#     - code-deployment
# 
# - include: symlink.yml
#   when: not deployment_setup_only
#   tags:
#     - code-deployment
# 
# - include: "{{ deployment_after_symlink_tasks_file | default('empty.yml') }}"
#   tags:
#     - code-deployment
# 
# - include: "{{ deployment_before_cleanup_tasks_file | default('empty.yml') }}"
#   tags:
#     - code-deployment
# 
# - include: cleanup.yml
#   when: not deployment_setup_only
#   tags:
#     - code-deployment
# 
# - include: "{{ deployment_after_cleanup_tasks_file | default('empty.yml') }}"
#   tags:
#     - code-deployment
# 
# ############
# # post_tasks
# ############
# 
# - include: handlers.yml
#   tags:
#     - code-deployment
# 
# - include: ec2-register.yml
#   when: deployment_rolling_elb_enabled
#   tags:
#     - code-deployment
# 
# - include: sensu.yml stash=false
#   when: deployment_sensu_enabled
#   tags:
#     - code-deployment
# 
# - include: mail.yml
#   when: deployment_mail_enabled
#   tags:
#     - code-deployment
# 
# - include: slack.yml state=end
#   when: slack
#   tags:
#     - code-deployment
# 
# - include: registry.yml state=end
#   when: deployment_registry
#   tags:
#     - code-deployment
