---

- name: Install required package for es backup | Ubuntu / Debian
  apt:
    name: '{{ item }}'
    cache_valid_time: 3600
    update_cache: yes 
    state: latest
  with_items:
    - python-dev
    - build-essential
    - python-pip
    - cron
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- pip: name=elasticsearch-curator state=present

# Ensure dateutil is installed for s3_lifecycle
- pip: name=python-dateutil state=present
  run_once: true

- pip: name=awscli state=latest
  when: _check_aws_cli|failed
