---
- name: Remove artifact if it exists locally.
  file: path=/tmp/s3_unzip.{{ deployment_archive_extension }} state=absent

- debug: msg="from S3 bucket={{ deployment_s3_bucket }} - object={{ deployment_s3_object }}.{{ deployment_archive_extension }}"

- name: S3 | Get object from S3
  s3: 
    bucket={{ deployment_s3_bucket }} 
    object={{ deployment_s3_object }}.{{ deployment_archive_extension }}
    dest=/tmp/s3_unzip.{{ deployment_archive_extension }}
    mode=get 
    region={{ deployment_s3_region }}

- apt: name=unzip
#  when: {{ deployment_archive_extension }} == "zip"

- name: Create unzip directory
  register: mktemp
  command: mktemp -d

- name: Unarchive archive
  unarchive: 
    src=/tmp/s3_unzip.{{ deployment_archive_extension }}
    dest={{ mktemp.stdout }}
    copy=no

- name: Create release directory
  file: name={{ deployment_release_path.stdout }} state=directory

- name: Move unarchive files
  shell: "mv {{ mktemp.stdout }}/{{deployment_additional_path}}/* {{ deployment_release_path.stdout }}"

- name: Remove temporary unarchive directory
  file: name={{ mktemp.stdout }} state=absent
